name: Warmer
on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 */1 * * *'
jobs:
  warmer:
    runs-on: ubuntu-latest
    steps:
      - name: branch checkout
        uses: actions/checkout@v2
      - run: npm install && node ./init.js https://observablehq.com/d/8719b09f9026e9f6 && ls -alh
      - uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: proof.jpg
